const express = require('express');
const router = express.Router();
const createCrudController = require('../controllers/crudController');
const createCrudService = require('../services/crudService');
const { BookIssue } = require('../models/Content');
const { authenticate, permissionGuard } = require('../middlewares/authMiddleware');
const ctrl = createCrudController(createCrudService(BookIssue, ['book_id','library_member_id']), 'BookIssue');
router.use(authenticate);
router.get('/',    permissionGuard('library.view'),   ctrl.getAll);
router.get('/:id', permissionGuard('library.view'),   ctrl.getById);
router.post('/',   permissionGuard('library.issue'),  ctrl.create);
router.put('/:id', permissionGuard('library.return'), ctrl.update);
module.exports = router;
