const express = require('express');
const router = express.Router();
const createCrudController = require('../controllers/crudController');
const createCrudService = require('../services/crudService');
const { SubjectAssign } = require('../models/Academic');
const { authenticate, permissionGuard } = require('../middlewares/authMiddleware');
const ctrl = createCrudController(createCrudService(SubjectAssign, ['class_setup_id','subject_id','teacher_id']), 'SubjectAssign');
router.use(authenticate);
router.get('/',    permissionGuard('subjects.view'),   ctrl.getAll);
router.get('/:id', permissionGuard('subjects.view'),   ctrl.getById);
router.post('/',   permissionGuard('subjects.create'), ctrl.create);
router.put('/:id', permissionGuard('subjects.edit'),   ctrl.update);
router.delete('/:id', permissionGuard('subjects.delete'), ctrl.delete);
module.exports = router;
