const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/transactionController');
const { authenticate, permissionGuard } = require('../middlewares/authMiddleware');
router.use(authenticate);
router.get('/',    permissionGuard('transactions.view'),   ctrl.getAll);
router.get('/:id', permissionGuard('transactions.view'),   ctrl.getById);
router.post('/',   permissionGuard('transactions.create'), ctrl.create);
router.put('/:id', permissionGuard('transactions.edit'),   ctrl.update);
router.delete('/:id', permissionGuard('transactions.delete'), ctrl.delete);
module.exports = router;
